// Package ids generates FileParcel identifiers and random tokens (DESIGN §1).
//
//   - Typed IDs: "<prefix>_<26 chars>" where the suffix is the lowercase
//     Crockford base32 encoding of a UUIDv7 (time-ordered, 74 random bits).
//     IDs generated by one process sort in creation order (monotonic within a
//     millisecond), so they are usable as keyset-pagination tie breakers.
//   - Blob IDs: 32 lowercase hex characters (128 random bits).
//   - Tokens: base62 strings with at least nBytes*8 bits of entropy.
//
// Tokens are never stored: store HashToken(tok) and compare with Equal.
package ids

import (
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"math"
	"strings"
	"sync"
	"time"
)

// ID prefixes (DESIGN §6). Use with New.
const (
	PrefixUser         = "usr" // users
	PrefixSession      = "ses" // sessions
	PrefixGroup        = "grp" // groups
	PrefixInvite       = "inv" // invites
	PrefixSpace        = "spc" // spaces
	PrefixNode         = "nod" // nodes (files and folders)
	PrefixVersion      = "ver" // file_versions
	PrefixGrant        = "gnt" // node_grants
	PrefixShare        = "shr" // shares (links and file requests)
	PrefixUploadBatch  = "upb" // upload_batches
	PrefixUploadFile   = "upf" // upload_files
	PrefixJob          = "job" // jobs
	PrefixBackup       = "bak" // backups
	PrefixToken        = "tok" // api_tokens
	PrefixPasskey      = "pky" // webauthn_credentials
	PrefixClientCert   = "ccr" // client_certs
	PrefixAudit        = "aud" // audit_log.id
	PrefixKEK          = "kek" // keyring
	PrefixMasterKey    = "mk"  // master key id (meta.mk_id)
	PrefixRecoveryCode = "rcv" // recovery_codes (not listed in DESIGN §6; added by foundation)
	PrefixRole         = "rol" // roles (custom)
)

// SuffixLen is the length of the base32 part of a typed ID.
const SuffixLen = 26

const crockford = "0123456789abcdefghjkmnpqrstvwxyz"

var decodeMap = func() [256]byte {
	var m [256]byte
	for i := range m {
		m[i] = 0xff
	}
	for i := 0; i < len(crockford); i++ {
		m[crockford[i]] = byte(i)
		m[strings.ToUpper(crockford[i : i+1])[0]] = byte(i)
	}
	return m
}()

var (
	uuidMu    sync.Mutex
	lastMs    int64
	lastSeq   uint16 // 12-bit counter in rand_a
	timeNowMs = func() int64 { return time.Now().UnixMilli() }
)

// NewUUIDv7 returns a RFC 9562 UUIDv7. Within one process, successive values
// are strictly increasing: rand_a is used as a 12-bit counter seeded randomly
// every millisecond (RFC 9562 §6.2 method 1); on counter overflow the
// timestamp is advanced by one millisecond.
func NewUUIDv7() [16]byte {
	var u [16]byte
	_, _ = rand.Read(u[6:])

	uuidMu.Lock()
	ms := timeNowMs()
	if ms > lastMs {
		lastMs = ms
		lastSeq = binary.BigEndian.Uint16(u[6:8]) & 0x07ff // leave headroom for increments
	} else {
		lastSeq++
		if lastSeq > 0x0fff {
			lastMs++
			lastSeq = binary.BigEndian.Uint16(u[6:8]) & 0x07ff
		}
	}
	ms, seq := lastMs, lastSeq
	uuidMu.Unlock()

	u[0] = byte(ms >> 40)
	u[1] = byte(ms >> 32)
	u[2] = byte(ms >> 24)
	u[3] = byte(ms >> 16)
	u[4] = byte(ms >> 8)
	u[5] = byte(ms)
	u[6] = 0x70 | byte(seq>>8)&0x0f // version 7
	u[7] = byte(seq)
	u[8] = u[8]&0x3f | 0x80 // variant 10
	return u
}

// Encode32 encodes 16 bytes as 26 lowercase Crockford base32 characters
// (big-endian, 2 leading zero pad bits; order preserving).
func Encode32(b [16]byte) string {
	hi := binary.BigEndian.Uint64(b[0:8])
	lo := binary.BigEndian.Uint64(b[8:16])
	var out [SuffixLen]byte
	for i := SuffixLen - 1; i >= 0; i-- {
		out[i] = crockford[lo&31]
		lo = lo>>5 | hi<<59
		hi >>= 5
	}
	return string(out[:])
}

// Decode32 is the inverse of Encode32 (case-insensitive).
func Decode32(s string) ([16]byte, error) {
	var b [16]byte
	if len(s) != SuffixLen {
		return b, errors.New("ids: bad length")
	}
	if decodeMap[s[0]] > 7 {
		return b, errors.New("ids: overflow")
	}
	var hi, lo uint64
	for i := 0; i < SuffixLen; i++ {
		v := decodeMap[s[i]]
		if v == 0xff {
			return b, errors.New("ids: invalid character")
		}
		hi = hi<<5 | lo>>59
		lo = lo<<5 | uint64(v)
	}
	binary.BigEndian.PutUint64(b[0:8], hi)
	binary.BigEndian.PutUint64(b[8:16], lo)
	return b, nil
}

// New returns a new typed ID: prefix + "_" + 26-char base32 UUIDv7.
func New(prefix string) string {
	return prefix + "_" + Encode32(NewUUIDv7())
}

// Valid reports whether id is a well-formed ID with the given prefix
// (lowercase suffix required).
func Valid(prefix, id string) bool {
	if len(id) != len(prefix)+1+SuffixLen || !strings.HasPrefix(id, prefix+"_") {
		return false
	}
	s := id[len(prefix)+1:]
	for i := 0; i < len(s); i++ {
		if strings.IndexByte(crockford, s[i]) < 0 {
			return false
		}
	}
	_, err := Decode32(s)
	return err == nil
}

// Prefix returns the prefix of a typed ID ("usr" for "usr_…"), or "" if id
// has no '_' separator.
func Prefix(id string) string {
	p, _, ok := strings.Cut(id, "_")
	if !ok {
		return ""
	}
	return p
}

// Time returns the creation time embedded in a typed ID (millisecond
// precision, UTC). ok is false for malformed IDs.
func Time(id string) (t time.Time, ok bool) {
	i := strings.IndexByte(id, '_')
	if i < 0 {
		return time.Time{}, false
	}
	b, err := Decode32(id[i+1:])
	if err != nil {
		return time.Time{}, false
	}
	ms := int64(b[0])<<40 | int64(b[1])<<32 | int64(b[2])<<24 | int64(b[3])<<16 | int64(b[4])<<8 | int64(b[5])
	return time.UnixMilli(ms).UTC(), true
}

// NewBlobID returns 32 lowercase hex characters (128 random bits).
func NewBlobID() string {
	b := make([]byte, 16)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

// ValidBlobID reports whether s is exactly 32 lowercase hex characters. Blob
// file paths are derived only from IDs that pass this check.
func ValidBlobID(s string) bool {
	if len(s) != 32 {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		if !(c >= '0' && c <= '9' || c >= 'a' && c <= 'f') {
			return false
		}
	}
	return true
}

// BlobIDBytes decodes a valid blob ID into its 16 raw bytes (the blob header
// field and the AAD use the raw form).
func BlobIDBytes(s string) ([]byte, error) {
	if !ValidBlobID(s) {
		return nil, errors.New("ids: invalid blob id")
	}
	return hex.DecodeString(s)
}

const base62 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

// TokenLen returns the number of base62 characters Token(nBytes) produces:
// ceil(nBytes*8 / log2(62)).
func TokenLen(nBytes int) int {
	return int(math.Ceil(float64(nBytes*8) / math.Log2(62)))
}

// Token returns a uniformly random base62 string carrying at least nBytes*8
// bits of entropy (32 bytes -> 43 chars). Characters are drawn by rejection
// sampling, so there is no modulo bias.
func Token(nBytes int) string {
	n := TokenLen(nBytes)
	out := make([]byte, 0, n)
	buf := make([]byte, n+n/4+8)
	for len(out) < n {
		_, _ = rand.Read(buf)
		for _, c := range buf {
			if c >= 248 { // 248 = 4*62: reject to keep uniformity
				continue
			}
			out = append(out, base62[c%62])
			if len(out) == n {
				break
			}
		}
	}
	return string(out)
}

// ValidToken reports whether s is non-empty and consists only of base62 characters.
func ValidToken(s string) bool {
	if s == "" {
		return false
	}
	for i := 0; i < len(s); i++ {
		if strings.IndexByte(base62, s[i]) < 0 {
			return false
		}
	}
	return true
}

// HashToken returns SHA-256(tok): the value stored in *_hash columns.
func HashToken(tok string) []byte {
	h := sha256.Sum256([]byte(tok))
	return h[:]
}

// Equal compares two strings in constant time (with respect to their content).
func Equal(a, b string) bool {
	return subtle.ConstantTimeCompare([]byte(a), []byte(b)) == 1
}

// EqualBytes compares two byte slices in constant time.
func EqualBytes(a, b []byte) bool {
	return subtle.ConstantTimeCompare(a, b) == 1
}
