package cli

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"mime"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"fileparcel/internal/core"
	"fileparcel/internal/ids"
)

func init() { Register(newClientCertCmd) }

func newClientCertCmd() *cobra.Command {
	cmd := groupCmd("client-cert", "Issue device certificates for mutual TLS",
		`Device certificates (mutual TLS) let only enrolled phones and computers
connect when mtls.mode is "optional" or "required". They are issued by a
separate client CA and saved as password-protected PKCS#12 (.p12) files that
phones and browsers import. Revoke one when a device is lost.`,
		`  fileparcel client-cert issue alice --name "Alice's phone" -o alice-phone.p12
  fileparcel client-cert list --user alice
  fileparcel client-cert revoke ccr_01j9zq3x4k6m8p0r2t4v6x8z0b`, "client-certs", "mtls")
	cmd.AddCommand(newClientCertIssueCmd(), newClientCertListCmd(), newClientCertRevokeCmd())
	setListHint(cmd, "fileparcel client-cert list --inactive")
	return cmd
}

// clientCertIssued is the decoded response of POST /admin/client-certs.
type clientCertIssued struct {
	Cert     *core.ClientCert `json:"cert"`
	P12      []byte           `json:"-"`
	Password string           `json:"password,omitempty"`
	Path     string           `json:"path"`
}

// decodeIssued accepts the response shapes a server may use: JSON
// {"cert":{…},"p12":"<base64>","password":"…"} (also "client_cert",
// "p12_base64", "pkcs12") or a raw application/x-pkcs12 body with the
// certificate id and password in headers.
func decodeIssued(resp *http.Response) (*clientCertIssued, error) {
	data, err := readStreamBody(resp, 8<<20)
	if err != nil {
		return nil, err
	}
	mt, _, _ := mime.ParseMediaType(resp.Header.Get("Content-Type"))
	out := &clientCertIssued{}
	if mt == "application/json" || (mt == "" && bytes.HasPrefix(bytes.TrimSpace(data), []byte("{"))) {
		var m map[string]json.RawMessage
		if err := json.Unmarshal(data, &m); err != nil {
			return nil, fmt.Errorf("decode response: %w", err)
		}
		for _, k := range []string{"cert", "client_cert", "certificate"} {
			if raw, ok := m[k]; ok {
				var cc core.ClientCert
				if json.Unmarshal(raw, &cc) == nil && cc.ID != "" {
					out.Cert = &cc
					break
				}
			}
		}
		if out.Cert == nil {
			var cc core.ClientCert
			if json.Unmarshal(data, &cc) == nil && cc.ID != "" {
				out.Cert = &cc
			}
		}
		for _, k := range []string{"p12", "p12_base64", "pkcs12"} {
			if raw, ok := m[k]; ok {
				var s string
				if err := json.Unmarshal(raw, &s); err != nil {
					continue
				}
				b, err := base64.StdEncoding.DecodeString(s)
				if err != nil {
					b, err = base64.RawURLEncoding.DecodeString(strings.TrimRight(s, "="))
				}
				if err == nil {
					out.P12 = b
					break
				}
			}
		}
		for _, k := range []string{"password", "p12_password"} {
			if raw, ok := m[k]; ok {
				_ = json.Unmarshal(raw, &out.Password)
				if out.Password != "" {
					break
				}
			}
		}
	} else {
		out.P12 = data
		out.Password = resp.Header.Get("X-FP-P12-Password")
		if id := resp.Header.Get("X-FP-Cert-ID"); id != "" {
			out.Cert = &core.ClientCert{ID: id}
		}
	}
	if len(out.P12) == 0 {
		return nil, errors.New("the server did not return the PKCS#12 file")
	}
	return out, nil
}

var unsafeFileChars = regexp.MustCompile(`[^A-Za-z0-9._-]+`)

// safeFileName turns a label into a portable file name component.
func safeFileName(s string) string {
	s = strings.Trim(unsafeFileChars.ReplaceAllString(s, "-"), "-.")
	if s == "" {
		return "client"
	}
	return Truncate(s, 60)
}

func newClientCertIssueCmd() *cobra.Command {
	var in core.ClientCertInput
	var out, expires string
	var force bool
	var pw *secretInput
	cmd := &cobra.Command{
		Use:     "issue <user>",
		Aliases: []string{"create"},
		Short:   "Issue a device certificate (.p12) for a user",
		Long: `Issue a device certificate for a user and save it as a PKCS#12 file (readable
only by you). The .p12 password is read from --password-stdin/--password-file
or generated by the server and printed once. --expires takes a duration
(365d, the default) or a date, at most 10 years ahead. --legacy uses the older
encryption that old Android and macOS versions need.

` + elevationNote,
		Example: `  fileparcel client-cert issue alice --name "Alice's phone"
  fileparcel client-cert issue bob --expires 90d -o bob.p12 --password-stdin < p12-pass.txt
  fileparcel client-cert issue carol --legacy`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("days") {
				if in.Days < 1 || in.Days > 3650 {
					return UsageError("--days must be between 1 and 3650")
				}
			} else {
				days, err := expiryDays(expires, time.Now())
				if err != nil {
					return err
				}
				in.Days = days
			}
			if pw.Given() {
				p, err := pw.Read(cmd, false)
				if err != nil {
					return err
				}
				in.Password = p
			}
			return WithClient(cmd, func(ctx context.Context, c *Client) error {
				u, err := resolveUser(ctx, c, args[0])
				if err != nil {
					return err
				}
				in.UserID = u.ID
				if in.Name == "" {
					in.Name = u.Username + " device"
				}
				dest := out
				if dest == "" {
					dest = safeFileName(u.Username+"-"+in.Name) + ".p12"
				}
				// Prepare the output before the certificate is issued: a
				// destination that cannot be written must fail here, not after
				// the server has created a certificate whose key would be lost.
				tmp, err := createP12Temp(dest, force)
				if err != nil {
					return err
				}
				defer os.Remove(tmp.Name()) // a no-op once renamed into place
				defer tmp.Close()
				body, _ := json.Marshal(in)
				resp, err := c.Stream(ctx, http.MethodPost, api("/admin/client-certs"), bytes.NewReader(body),
					http.Header{"Content-Type": {"application/json"}, "Accept": {"application/json, application/x-pkcs12"}})
				if err != nil {
					return err
				}
				res, err := decodeIssued(resp)
				if err != nil {
					return err
				}
				if res.Password == "" {
					res.Password = in.Password
				}
				if err := publishP12(tmp, dest, res.P12, force); err != nil {
					return revokeUnwritten(ctx, c, res, err)
				}
				res.Path = dest
				showPassword := res.Password != "" && in.Password == ""
				if !showPassword {
					res.Password = ""
				}
				return Print(cmd, res, func(w io.Writer) error {
					id := ""
					if res.Cert != nil {
						id = " " + res.Cert.ID
					}
					Successf(cmd, "issued client certificate%s for %q → %s", id, u.Username, dest)
					if showPassword {
						fmt.Fprintf(w, "P12 password: %s\n", res.Password)
						Infof(cmd, "The password is shown only once; the device asks for it when importing the file.")
					}
					return nil
				})
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&in.Name, "name", "", `a name for the device (default "<user> device")`)
	f.StringVar(&expires, "expires", "365d", "validity: a duration (90d, 2w) or a date (2027-12-31); at most 10 years")
	// Legacy: --days N is --expires Nd (legacy.go).
	f.IntVar(&in.Days, "days", 365, "validity in days")
	_ = f.MarkHidden("days")
	cmd.MarkFlagsMutuallyExclusive("expires", "days")
	addOutputFlag(cmd, &out, "output .p12 file (default: <user>-<name>.p12)")
	pw = addSecretFlags(cmd, "password", ".p12 password", secretOpts{})
	f.BoolVar(&in.Legacy, "legacy", false, "legacy PKCS#12 encryption for old Android/macOS")
	addForceFlag(cmd, &force, "overwrite an existing output file")
	return cmd
}

// expiryDays turns the --expires of a client certificate into whole days
// (rounded up) for ClientCertInput.Days: at least 1, at most 3650. Client
// certificates must expire ("never" is refused).
func expiryDays(expires string, now time.Time) (int, error) {
	exp, _, err := parseExpiry(expires, now, false)
	if err != nil {
		return 0, err
	}
	if exp == nil {
		return 0, UsageError("--expires needs a value (365d, 90d or a date)")
	}
	days := int(math.Ceil(exp.Sub(now).Hours() / 24))
	if days < 1 || days > 3650 {
		return 0, UsageError("--expires must be between 1 day and 10 years ahead")
	}
	return days, nil
}

// createP12Temp checks that dest may be written (not a directory, not an
// existing file without --force) and creates the temporary file the .p12 is
// written to, in dest's directory, so a missing or read-only directory is
// reported before anything is issued. The existing dest is left alone until
// the new file replaces it.
func createP12Temp(dest string, force bool) (*os.File, error) {
	if st, err := os.Lstat(dest); err == nil {
		if st.IsDir() {
			return nil, fmt.Errorf("%s is a directory", dest)
		}
		if !force {
			return nil, fmt.Errorf("%s already exists (use --force or --output)", dest)
		}
	}
	return os.CreateTemp(filepath.Dir(dest), "."+filepath.Base(dest)+".*"+partialSuffix)
}

// publishP12 writes data to tmp with mode 0600 and renames it over dest. A
// rename replaces dest instead of rewriting it, so the result is 0600 even
// when --force overwrites a more permissive file, and a symlink at dest is
// replaced rather than written through.
func publishP12(tmp *os.File, dest string, data []byte, force bool) error {
	_, err := tmp.Write(data)
	if err == nil {
		err = tmp.Chmod(0o600)
	}
	if err == nil {
		err = tmp.Sync()
	}
	if cerr := tmp.Close(); err == nil {
		err = cerr
	}
	if err != nil {
		return err
	}
	if !force && fileExists(dest) {
		return fmt.Errorf("%s already exists (use --force or --output)", dest)
	}
	return os.Rename(tmp.Name(), dest)
}

// revokeUnwritten handles a .p12 that could not be written after the server
// issued the certificate: its private key exists nowhere else, so the
// certificate is revoked again, or named so that it can be revoked by hand.
func revokeUnwritten(ctx context.Context, c *Client, res *clientCertIssued, werr error) error {
	if res.Cert == nil || res.Cert.ID == "" {
		return fmt.Errorf("%w (the certificate was issued; revoke it: \"fileparcel client-cert list\", then \"client-cert revoke <id>\")", werr)
	}
	id := res.Cert.ID
	err := c.Do(ctx, http.MethodDelete, api("/admin/client-certs/"+pathEsc(id), "reason", "the .p12 file could not be written"), nil, nil)
	if err != nil {
		return fmt.Errorf("%w; the issued certificate %s could not be revoked either (%v): run \"fileparcel client-cert revoke %s\"", werr, id, err, id)
	}
	return fmt.Errorf("%w (the issued certificate %s was revoked again)", werr, id)
}

func newClientCertListCmd() *cobra.Command {
	var user string
	var inactive bool
	cmd := &cobra.Command{
		Use:     "list",
		Aliases: []string{"ls"},
		Short:   "List device certificates",
		Long:    "List issued device certificates; revoked and expired ones only with --inactive.",
		Example: `  fileparcel client-cert list
  fileparcel client-cert list --user alice --inactive --json`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return WithClient(cmd, func(ctx context.Context, c *Client) error {
				uid := ""
				if user != "" {
					u, err := resolveUser(ctx, c, user)
					if err != nil {
						return err
					}
					uid = u.ID
				}
				certs, err := listAll[core.ClientCert](ctx, c, api("/admin/client-certs", "user_id", uid, "limit", limitParam(0)), 0)
				if err != nil {
					return err
				}
				now := time.Now()
				kept := certs[:0]
				for _, cc := range certs {
					if uid != "" && cc.UserID != "" && cc.UserID != uid {
						continue
					}
					if inactive || (cc.RevokedAt == nil && cc.NotAfter.After(now)) {
						kept = append(kept, cc)
					}
				}
				certs = kept
				return Print(cmd, certs, func(w io.Writer) error {
					if len(certs) == 0 {
						Infof(cmd, "no client certificates")
						return nil
					}
					t := NewTable("ID", "USER", "NAME", "SERIAL", "EXPIRES", "STATUS", "LAST SEEN")
					for _, cc := range certs {
						status := "valid"
						switch {
						case cc.RevokedAt != nil:
							status = "revoked"
						case !cc.NotAfter.After(now):
							status = "expired"
						}
						t.Add(cc.ID, Dash(cc.Username), cc.Name, Truncate(cc.Serial, 20), cc.NotAfter, status, cc.LastSeenAt)
					}
					return t.Render(w)
				})
			})
		},
	}
	cmd.Flags().StringVar(&user, "user", "", "only the certificates of this user")
	addInactiveFlag(cmd, &inactive, "include revoked and expired certificates")
	return cmd
}

func newClientCertRevokeCmd() *cobra.Command {
	var reason string
	cmd := &cobra.Command{
		Use:   "revoke <id|serial>",
		Short: "Revoke a device certificate",
		Long: `Revoke a device certificate by id (ccr_…) or serial number; the device can no
longer connect while mutual TLS is required.`,
		Example: `  fileparcel client-cert revoke ccr_01j9zq3x4k6m8p0r2t4v6x8z0b
  fileparcel client-cert revoke 5f:3a:… --reason "phone lost"`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return WithClient(cmd, func(ctx context.Context, c *Client) error {
				id := strings.TrimSpace(args[0])
				if !ids.Valid(ids.PrefixClientCert, id) {
					certs, err := listAll[core.ClientCert](ctx, c, api("/admin/client-certs", "limit", limitParam(0)), 0)
					if err != nil {
						return err
					}
					norm := func(s string) string { return strings.ToLower(strings.NewReplacer(":", "", " ", "").Replace(s)) }
					found := ""
					for _, cc := range certs {
						if norm(cc.Serial) == norm(id) {
							found = cc.ID
						}
					}
					if found == "" {
						return core.Errorf(core.ErrNotFound, "no client certificate with id or serial %q", id)
					}
					id = found
				}
				if err := c.Do(ctx, http.MethodDelete, api("/admin/client-certs/"+pathEsc(id), "reason", reason), nil, nil); err != nil {
					return err
				}
				return done(cmd, map[string]string{"revoked": id}, "revoked client certificate %s", id)
			})
		},
	}
	cmd.Flags().StringVar(&reason, "reason", "", "reason recorded with the revocation")
	return cmd
}
