package clikit

import (
	"bufio"
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/spf13/cobra"
)

// MarkdownOptions tunes WriteMarkdown.
type MarkdownOptions struct {
	// Title is the document heading (default "Command reference").
	Title string
	// Intro is an optional paragraph printed below the title.
	Intro string
	// BaseLevel is the heading level of top-level commands (default 2; the
	// title uses BaseLevel-1, deeper commands BaseLevel+depth, capped at 6).
	BaseLevel int
}

// WriteMarkdown writes a Markdown reference of the command tree below root:
// a table of contents, the global (persistent root) flags, then every
// visible command (depth first, sorted by name) with its description, usage,
// aliases, subcommands, flags and examples, and last the help topics
// ("fileparcel help paths": root children that are not commands) with their
// text. When the root has command groups, the contents list the top-level
// commands under the group titles, in group order. Hidden, deprecated and
// help commands are skipped. The output is deterministic (no timestamps, no
// environment-dependent values).
func WriteMarkdown(w io.Writer, root *cobra.Command, o MarkdownOptions) error {
	if o.Title == "" {
		o.Title = "Command reference"
	}
	if o.BaseLevel < 2 || o.BaseLevel > 5 {
		o.BaseLevel = 2
	}
	bw := bufio.NewWriter(w)
	p := func(format string, a ...any) { fmt.Fprintf(bw, format, a...) }

	root.InitDefaultHelpFlag()
	cmds := collect(root)
	// Merge the persistent flags of the ancestors into every command first:
	// cobra does this lazily, and UseLine ("[flags]") depends on it.
	for _, c := range cmds {
		c.InheritedFlags()
		c.LocalFlags()
	}

	p("%s %s\n\n", strings.Repeat("#", o.BaseLevel-1), o.Title)
	p("<!-- Generated by `%s docs --markdown`. Do not edit by hand. -->\n\n", root.Name())
	if o.Intro != "" {
		p("%s\n\n", strings.TrimSpace(o.Intro))
	}

	// Contents: every command below its top-level one; the top-level
	// commands under their group titles when the root has groups.
	topics := helpTopics(root)
	p("%s Contents\n\n", strings.Repeat("#", o.BaseLevel))
	p("- [Global flags](#global-flags)\n")
	if len(topics) > 0 {
		p("- [Help topics](#help-topics)\n")
	}
	for _, sec := range contentsSections(root) {
		if sec.title != "" {
			p("\n**%s**\n\n", mdEscape(sec.title))
		}
		for _, top := range sec.cmds {
			for _, c := range collect(top) {
				indent := strings.Repeat("  ", depth(c)-1)
				p("%s- [`%s`](#%s) — %s\n", indent, c.CommandPath(), Anchor(c.CommandPath()), cell(c.Short))
			}
		}
	}
	p("\n")

	// Global flags.
	p("%s Global flags\n\n", strings.Repeat("#", o.BaseLevel))
	p("These flags are accepted by every command.\n\n")
	writeFlagTable(bw, commandFlags(root, flagsPersistent))
	p("\n")

	for _, c := range cmds {
		if c == root {
			continue
		}
		level := min(o.BaseLevel+depth(c)-1, 6)
		p("%s %s\n\n", strings.Repeat("#", level), c.CommandPath())
		if c.Short != "" {
			p("%s\n\n", mdEscape(ensurePeriod(c.Short)))
		}
		if long := strings.TrimSpace(c.Long); long != "" && long != strings.TrimSpace(c.Short) {
			p("%s\n\n", mdLong(long))
		}
		p("**Usage**\n\n```\n%s\n```\n\n", usageLines(c))
		if len(c.Aliases) > 0 {
			p("**Aliases:** %s\n\n", "`"+strings.Join(c.Aliases, "`, `")+"`")
		}
		if subs := visibleChildren(c); len(subs) > 0 {
			p("**Subcommands**\n\n| Command | Description |\n|---|---|\n")
			for _, s := range subs {
				p("| [`%s`](#%s) | %s |\n", s.Name(), Anchor(s.CommandPath()), cell(s.Short))
			}
			p("\n")
		}
		if fs := commandFlags(c, flagsLocal); len(fs) > 0 {
			p("**Flags**\n\n")
			writeFlagTable(bw, fs)
			p("\n")
		}
		if fs := commandFlags(c, flagsInherited); len(fs) > 0 {
			p("**Inherited flags**\n\n")
			writeFlagTable(bw, fs)
			p("\n")
		}
		if ex := strings.Trim(c.Example, "\n"); strings.TrimSpace(ex) != "" {
			p("**Examples**\n\n```sh\n%s\n```\n\n", dedent(ex))
		}
	}

	// Help topics: their text as the terminal shows it.
	if len(topics) > 0 {
		p("%s Help topics\n\n", strings.Repeat("#", o.BaseLevel))
		for _, t := range topics {
			p("%s %s help %s\n\n", strings.Repeat("#", min(o.BaseLevel+1, 6)), root.Name(), t.Name())
			if t.Short != "" {
				p("%s\n\n", mdEscape(ensurePeriod(t.Short)))
			}
			if long := strings.Trim(t.Long, "\n"); strings.TrimSpace(long) != "" {
				p("```text\n%s\n```\n\n", long)
			}
		}
	}
	return bw.Flush()
}

// contentsSection is one group of the contents: a title ("" for the
// commands of a root without groups) and its top-level commands.
type contentsSection struct {
	title string
	cmds  []*cobra.Command
}

// contentsSections splits the visible top-level commands by the root's
// groups, in group order; commands without a group follow under "More
// commands" (cobra's word).
func contentsSections(root *cobra.Command) []contentsSection {
	tops := visibleChildren(root)
	if len(root.Groups()) == 0 {
		return []contentsSection{{cmds: tops}}
	}
	var out []contentsSection
	for _, g := range root.Groups() {
		sec := contentsSection{title: strings.TrimSuffix(strings.TrimSpace(g.Title), ":")}
		for _, c := range tops {
			if c.GroupID == g.ID {
				sec.cmds = append(sec.cmds, c)
			}
		}
		if len(sec.cmds) > 0 {
			out = append(out, sec)
		}
	}
	rest := contentsSection{title: "More commands"}
	for _, c := range tops {
		if !slices.ContainsFunc(root.Groups(), func(g *cobra.Group) bool { return g.ID == c.GroupID }) {
			rest.cmds = append(rest.cmds, c)
		}
	}
	if len(rest.cmds) > 0 {
		out = append(out, rest)
	}
	return out
}

// helpTopics returns the help topics of root ("fileparcel help paths"):
// children that only carry a text, sorted by name.
func helpTopics(root *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, c := range root.Commands() {
		if c.IsAdditionalHelpTopicCommand() && !c.Hidden && c.Name() != "help" {
			out = append(out, c)
		}
	}
	slices.SortFunc(out, func(a, b *cobra.Command) int { return strings.Compare(a.Name(), b.Name()) })
	return out
}

// collect returns root and every visible descendant, depth first, children
// sorted by name.
func collect(root *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		out = append(out, c)
		for _, s := range visibleChildren(c) {
			walk(s)
		}
	}
	walk(root)
	return out
}

// visibleChildren returns the documented subcommands of c, sorted by name.
// Help topics ("fileparcel help paths") are not commands.
func visibleChildren(c *cobra.Command) []*cobra.Command {
	var subs []*cobra.Command
	for _, s := range c.Commands() {
		if s.Hidden || s.Deprecated != "" || s.Name() == "help" || strings.HasPrefix(s.Name(), "__") || s.IsAdditionalHelpTopicCommand() {
			continue
		}
		subs = append(subs, s)
	}
	slices.SortFunc(subs, func(a, b *cobra.Command) int { return strings.Compare(a.Name(), b.Name()) })
	return subs
}

func depth(c *cobra.Command) int {
	d := 0
	for p := c; p.HasParent(); p = p.Parent() {
		d++
	}
	return d
}

// usageLines renders the usage line(s) of c: "fileparcel user add <name> [flags]"
// for runnable commands and "fileparcel user <command>" for groups.
func usageLines(c *cobra.Command) string {
	var lines []string
	if c.Runnable() {
		lines = append(lines, c.UseLine())
	}
	if len(visibleChildren(c)) > 0 {
		lines = append(lines, c.CommandPath()+" <command>")
	}
	if len(lines) == 0 {
		lines = append(lines, c.CommandPath())
	}
	return strings.Join(lines, "\n")
}

// flagInfo is the documented view of one flag.
type flagInfo struct {
	Name, Shorthand, Type, Default, Usage string
}

// flagVisitor matches *pflag.FlagSet without importing pflag directly (it is
// an indirect module dependency; the element type is inferred from cobra's
// return values).
type flagVisitor[F any] interface{ VisitAll(fn func(F)) }

func flagsOf[F any](fs flagVisitor[F]) []F {
	var out []F
	fs.VisitAll(func(f F) { out = append(out, f) })
	return out
}

// Flag sets of a command, for commandFlags.
const (
	flagsLocal      = "local"      // flags defined on the command itself (incl. its persistent ones)
	flagsInherited  = "inherited"  // inherited from ancestors, minus the root's global flags
	flagsPersistent = "persistent" // persistent flags defined on the command (root: global flags)
)

// commandFlags returns the visible flags of one set of c (help excluded),
// sorted by name. The local set includes persistent flags defined on c
// itself (they are documented there and as inherited on its children).
func commandFlags(c *cobra.Command, which string) []flagInfo {
	fs := c.LocalFlags()
	switch which {
	case flagsInherited:
		fs = c.InheritedFlags()
	case flagsPersistent:
		fs = c.PersistentFlags()
	}
	globals := c.Root().PersistentFlags()
	var out []flagInfo
	for _, f := range flagsOf(fs) {
		if f.Hidden || f.Name == "help" {
			continue
		}
		if which == flagsInherited && globals.Lookup(f.Name) != nil {
			continue
		}
		fi := flagInfo{Name: f.Name, Type: f.Value.Type(), Default: f.DefValue, Usage: f.Usage}
		if f.Shorthand != "" && f.ShorthandDeprecated == "" {
			fi.Shorthand = f.Shorthand
		}
		if f.Deprecated != "" {
			fi.Usage += " (deprecated: " + f.Deprecated + ")"
		}
		out = append(out, fi)
	}
	slices.SortFunc(out, func(a, b flagInfo) int { return strings.Compare(a.Name, b.Name) })
	return out
}

func writeFlagTable(w io.Writer, flags []flagInfo) {
	fmt.Fprint(w, "| Flag | Type | Default | Description |\n|---|---|---|---|\n")
	for _, f := range flags {
		name := "--" + f.Name
		if f.Shorthand != "" {
			name = "-" + f.Shorthand + ", " + name
		}
		typ := f.Type
		switch typ {
		case "stringSlice", "stringArray":
			typ = "strings"
		case "bool":
			typ = ""
		}
		def := f.Default
		switch def {
		case "", "false", "[]", "0", "0s":
			def = ""
		}
		if def != "" {
			def = "`" + def + "`"
		}
		fmt.Fprintf(w, "| `%s` | %s | %s | %s |\n", name, typ, def, cell(f.Usage))
	}
}

// cell escapes a string for a Markdown table cell.
func cell(s string) string {
	s = mdEscape(strings.ReplaceAll(strings.TrimSpace(s), "\n", " "))
	s = strings.ReplaceAll(s, "|", `\|`)
	return s
}

// mdEscape escapes plain help text for Markdown: placeholders such as
// <HOME> or <user> would otherwise be raw HTML tags (dropped when
// rendered), "&amp;" an entity and "backup.* … acme.*" emphasis.
var mdEscape = strings.NewReplacer(`\`, `\\`, "<", `\<`, "&", `\&`, "*", `\*`).Replace

// mdLong renders a command's Long help text. Plain lines are escaped
// (mdEscape); a run of indented lines (path lists, aligned columns,
// "  # …" shell comments) becomes a fenced block, which keeps its layout
// and its placeholders, and whose "#" lines do not turn into headings.
func mdLong(long string) string {
	lines := strings.Split(long, "\n")
	indented := func(l string) bool { return strings.HasPrefix(l, " ") || strings.HasPrefix(l, "\t") }
	var out []string
	for i := 0; i < len(lines); {
		if !indented(lines[i]) {
			l := mdEscape(lines[i])
			if strings.HasPrefix(l, "#") || strings.HasPrefix(l, ">") {
				l = `\` + l // not a heading or a quote
			}
			out = append(out, l)
			i++
			continue
		}
		// The run ends before a blank line that no indented line follows.
		end := i
		for j := i; j < len(lines); j++ {
			if indented(lines[j]) {
				end = j + 1
			} else if strings.TrimSpace(lines[j]) != "" {
				break
			}
		}
		out = append(out, "```text", dedent(strings.Join(lines[i:end], "\n")), "```")
		i = end
	}
	return strings.Join(out, "\n")
}

func ensurePeriod(s string) string {
	s = strings.TrimSpace(s)
	if s == "" || strings.HasSuffix(s, ".") || strings.HasSuffix(s, "!") || strings.HasSuffix(s, "?") {
		return s
	}
	return s + "."
}

// dedent removes the common leading whitespace of the non-empty lines.
func dedent(s string) string {
	lines := strings.Split(s, "\n")
	prefix := -1
	for _, l := range lines {
		if strings.TrimSpace(l) == "" {
			continue
		}
		n := len(l) - len(strings.TrimLeft(l, " \t"))
		if prefix < 0 || n < prefix {
			prefix = n
		}
	}
	if prefix <= 0 {
		return s
	}
	for i, l := range lines {
		if len(l) >= prefix {
			lines[i] = l[prefix:]
		} else {
			lines[i] = strings.TrimLeft(l, " \t")
		}
	}
	return strings.Join(lines, "\n")
}

// Anchor returns the GitHub-style heading anchor of a heading text:
// lowercase, spaces to "-", everything except letters, digits, "-" and "_"
// dropped ("fileparcel client-cert issue" → "fileparcel-client-cert-issue").
func Anchor(heading string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(heading) {
		switch {
		case r == ' ':
			b.WriteByte('-')
		case r == '-' || r == '_' || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9'):
			b.WriteRune(r)
		case r > 127:
			b.WriteRune(r)
		}
	}
	return b.String()
}
